### ISSUE TITLE
kernel source and uboot？

### ISSUE THREAD

**Issue by smallpotato000** [baosong818/Centos7-FT1500a#1]
Do you have official kernel source code, as well as uboot, and/or grub？
I ported the kernel myself, however it is not complete, and I still cannot get radeonfb working. Now I can boot via com1 and get a working initrd busybox shell.

**Comment by baosong818** [comment]
I submit the update, I am also looking for Internet resources.

**Comment by baosong818** [comment]
linux-4.15.18-rc3-arch64-bochtec.com.tar.gz


This is the source code. I don’t know if there is something in it. Internet resources will not change.

**Comment by baosong818** [comment]
都china，你就不能说中文啊
linux-4.15.18-rc3-arch64-bochtec.com.tar.gz

这个包就是内核源码，里面有啥我也不知道，具体自己看
