### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by tom0501** [baosong818/Centos7-FT1500a#2]
我尝试了一下，无法下载，请问有别的路径吗？

**Comment by baosong818** [comment]
请问你是飞腾的技术人员还是？

**Comment by tom0501** [comment]
不是，我是一个普通的开发人员，不是飞腾的人。只是想看看能不能自己搭建一个系统，因为用银河麒麟不是很顺手，而且没有源码有些东西实现不了。



---原始邮件---
发件人: "钚钉钬影"<notifications@github.com&gt;
发送时间: 2019年12月5日(周四) 下午2:33
收件人: "baosong818/Centos7-FT1500a"<Centos7-FT1500a@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tom0501"<303401267@qq.com&gt;;
主题: Re: [baosong818/Centos7-FT1500a] 无法下载 (#2)



请问你是飞腾的技术人员还是？

**Comment by baosong818** [comment]
链接: https://pan.baidu.com/s/1CqZAGMZUu_wnMDzL6zBF8w 提取码: gjj4

**Comment by baosong818** [comment]
我是不是特仁义，哈哈哈哈

**Comment by tom0501** [comment]
哥们儿绝对的好人！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"钚钉钬影"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午2:39
收件人:&nbsp;"baosong818/Centos7-FT1500a"<Centos7-FT1500a@noreply.github.com&gt;;
抄送:&nbsp;"303401267"<303401267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baosong818/Centos7-FT1500a] 无法下载 (#2)




我是不是特仁义，哈哈哈哈

**Comment by baosong818** [comment]
赶紧保存啊，就7天

**Comment by tom0501** [comment]
马上下载，我转存了应该就好是吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"钚钉钬影"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午2:41
收件人:&nbsp;"baosong818/Centos7-FT1500a"<Centos7-FT1500a@noreply.github.com&gt;;
抄送:&nbsp;"303401267"<303401267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [baosong818/Centos7-FT1500a] 无法下载 (#2)




赶紧保存啊，就7天
