### ISSUE TITLE
git lfs fetch错误

### ISSUE THREAD

**Issue by smallpotato000** [baosong818/Centos7-FT1500a#3]
无法下载必要的文件
$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/baosong818/Centos7-FT1500a.git/info/lfs'

**Comment by baosong818** [comment]
链接: https://pan.baidu.com/s/19SG5D69SyC4VwNJXEPbcsA 提取码: 106h

**Comment by smallpotato000** [comment]
谢谢
我测试一下没啥问题的话就切换到这个版本的kernel，不再维护我自己胡乱移植的那个了

**Comment by baosong818** [comment]
我这个也不知道哪里来的，互联网资源
