### ISSUE TITLE
FT1500A 移植

### ISSUE THREAD

**Issue by xspython** [baosong818/Centos7-FT1500a#4]
您好:
    博主,github上面的东西是不是上传的不全,有没有完整版本,感谢

**Comment by xspython** [comment]
有没有具体的内核配置文档

**Comment by baosong818** [comment]
全了啊，linux-4.15.18-rc3-arch64-bochtec.com.tar.gz这不就是新内核嘛
具体配置什么，百度、谷歌吧，我也是找的网络资源

**Comment by xspython** [comment]
您看下 github下来下来才几KB。。 您能给我个百度云盘的地址吗

**Comment by xspython** [comment]
博主 有没有QQ 之类的 加个好友 咨询下

**Comment by baosong818** [comment]
链接: https://pan.baidu.com/s/17OJShVKYa9jnZ6XWYT0P9A 提取码: 7hqk

8410405
