### ISSUE TITLE
FT1500A U盘安装系统

### ISSUE THREAD

**Issue by xspython** [baosong818/Centos7-FT1500a#5]
博主：
   我用了您这个这个ISO 安装系统发现报错,需要重新刷U-BOOT吗？
![111123123](https://user-images.githubusercontent.com/10435263/78224672-82e6d280-74fb-11ea-9867-41fc3a1385a8.jpg)

**Comment by baosong818** [comment]
里面有个iso，你烧录到u盘安装完了就是centos7了啊

**Comment by xspython** [comment]
不行烧录过了。。他这个默认要找casper\uimage  我估计要重新烧录下flash

**Comment by ThinkingXuan** [comment]
@xspython  请问这个安装问题你解决了吗？
